Implementing support for custom sample apps, locally and via remote git repository
homeport/gonut pull request #86
Opened 2019-08-12 14:32 UTC by m-lukas

- Replace sub-command structure (php, golang, all ...) with args
-> add support for specifying multiple apps at one
- Implement url lookup, use of git functionality, local download
- Refactor ExitGonut
- Fix hostname bug in sample app pinging
- Add test cases for localization functions

2019-08-27 18:48 UTC, HeavyWombat requested changes
Thanks for the PR. Could you have a look at the additional aliases that seem wrong?

2019-08-27 18:48 UTC, HeavyWombat commented on internal/gonut/cmd/push.go
> +		aliases:       []string{"node"},
Is that a copy/paste error? That should not be an alias for that language.

2019-08-27 18:48 UTC, HeavyWombat commented on internal/gonut/cmd/push.go
> +		aliases:       []string{"node"},
Is that a copy/paste error? That should not be an alias for that language.

2019-08-27 18:48 UTC, HeavyWombat commented on internal/gonut/cmd/push.go
> +		aliases:       []string{"node"},
Is that a copy/paste error? That should not be an alias for that language.

2019-09-02 12:39 UTC, m-lukas commented
Fixed :)

2019-09-02 18:37 UTC, HeavyWombat approved these changes

2019-09-02 18:37 UTC, merged